import React, {useState , useEffect} from 'react';
// import  Nav from '../../components/Nav/Nav';
import  Card from '../../components/Card/Card';
import DefaultLayout from '../../layouts/Default';
import Head from 'next/head'

export default function Pets() {
  const [cats, setCats] = useState([]);

  const fetchCats = async () => {
    const response = await fetch("/api/cats");
    const data = await response.json();
   
    setCats([...cats].concat(data));
    //  console.log(data)
     console.log("cats",cats)
  };

  useEffect(() => {
    fetchCats();
  }, []);


return (
  <>
       <Head>
        <title>ASPCA adoption</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <DefaultLayout>
  <div className='container mt-5 '>
      <div style={{display:'flex', flexWrap:"wrap",}}>
      pet page
     
      {cats.map((cat)=>{
        return(
          <Card 
            name={cat.name}
            id={cat.id}
            phone={cat.phone}
            image={cat.image}
            email={cat.email}
          
          
          
          />
        )

      })}
</div>
   </div>
   </DefaultLayout>
   </>
);

};
// https://www.youtube.com/watch?v=6HTs8HtZMt0 59:37